#range - generates a sequence of numbers. It can take one, two, or three arguments. The syntax of the range function is as follows:
#range(stop) - generates a sequence of numbers from 0 to stop-1.
#range(start, stop) - generates a sequence of numbers from start to stop-1.
#range(start, stop, step) - generates a sequence of numbers from start to stop-1, with a step of step.

#1.HERE WE PRINT THE NUMBERS FROM 0 TO 9 USING THE RANGE FUNCTION-
for i in range(10):
    print(i) #output: 0 1 2 3 4 5 6 7 8 9

#2.HERE WE PRINT THE NUMBERS FROM 1 TO 10 USING THE RANGE FUNCTION-
for i in range(1, 11):
    print(i) #output: 1 2 3 4 5 6 7 8 9 10

#3.HERE WE PRINT THE NUMBERS FROM 1 TO 10 WITH A STEP OF 2 USING THE RANGE FUNCTION-
for i in range(1, 11, 2):
    print(i) #output: 1 3 5 7 9

#4.HERE WE PRINT THE NUMBERS FROM 10 TO 1 IN REVERSE ORDER USING THE RANGE FUNCTION-
for i in range(10, 0, -1):
    print(i) #output: 10 9 8 7 6 5 4 3 2 1 .

#5.like the other we can use the index and count and slice with the range function as well-

r=range(10)
print(r[2]) #output: 2 - The index 2 of the range object r corresponds to the value 2 in the sequence generated by the range function, which starts from 0 and increments by 1.
print(r[2:5]) #output: range(2, 5) - The
print(r[:3]) #output: range(0, 3) - The slicing syntax [:3] is used to create a new range object that includes the first three elements of the original range object r, which corresponds to the values 0, 1, and 2 in the sequence generated by the range function.
print(r.count(2)) #output: 1 - The count() method counts the number of occurrences of the value 2 in the range object r, which is 1 because the value 2 appears once in the sequence generated by the range function.
print(r.index(2)) #output: 2 - The index() method returns the index of the first occurrence of the value 2 in the range object r, which is 2 because the value 2 is located at index 2 in the sequence generated by the range function.

#in the range the index number starts from 0 and the last number is stop-1. so the range(10) generates a sequence of numbers from 0 to 9, and the index of the value 2 is 2 because it is located at index 2 in the sequence.

#6.we can also use the range function to create a list of numbers by converting the range object to a list using the list() constructor:
r=range(10)
numbers_list = list(r)
print(numbers_list) #output: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] - The list() constructor converts the range object r into a list of numbers from 0 to 9, which is then printed as the output.

#membership testing-

r=range(0,10,2)
print(6 in r)
print(7 in r)
#output: True False - The in operator checks if the value 6 is present in the range object r, which generates a sequence of even numbers from 0 to 9. Since 6 is an even number and is included in the sequence, the expression 6 in r evaluates to True. On the other hand, since 7 is not an even number and is not included in the sequence generated by the range function, the expression 7 in r evaluates to False.


#length of the range object -

r=range(0,10,2)
print(len(r)) #output: 5 - The len() function returns the number of elements in the range object r, which generates a sequence of even numbers from 0 to 9. The sequence includes the numbers 0, 2, 4, 6, and 8, resulting in a total of 5 elements in the range object. Therefore, len(r) returns 5 as the output.