
#                               Text 

#A  file that stores readable data is called a text file 

#This is return in .txt format

file = open("demo.txt", "w")
file.write("Hello Python")
file.close()

#example - csv files (.csv), log files (.log), configuration files (.cfg), and many other types of files that contain data in a format that is intended to be human-readable.

#csv- comma separated values - a file format that uses commas to separate values. It is commonly used for storing tabular data, such as spreadsheets or databases. Each line in a csv file represents a row of data, and the values in each row are separated by commas. For example:

#log files - a file format that is used to store log messages generated by applications, servers, or other software. Log files typically contain information about events, errors, or other activities that occur within the software. They are often used for troubleshooting and monitoring purposes.

#configuration files - a file format that is used to store settings and preferences for software applications. Configuration files typically contain key-value pairs that define various parameters and options for the software. They are often used to customize the behavior of applications without modifying the source code.

#json files - a file format that is used to store data in a structured, human-readable format. JSON (JavaScript Object Notation) is a lightweight data interchange format that is easy for humans to read and write, and easy for machines to parse and generate. JSON files typically contain data in the form of key-value pairs, arrays, and nested objects. They are commonly used for storing and exchanging data between web applications and servers.

#xml files - a file format that is used to store data in a structured, human-readable format. XML (eXtensible Markup Language) is a markup language that defines a set of rules for encoding documents in a format that is both human-readable and machine-readable. XML files typically contain data in the form of elements, attributes, and nested structures. They are commonly used for storing and exchanging data between applications and systems.


#                              Binary

#A file that stores data in a format that is not human-readable is called a binary file. Binary files can contain any type of data, such as images, audio, video, or executable programs. They are typically used for storing complex data structures or for efficient storage and retrieval of data.

#A file that stores data in machine-readable format (0s and 1s), not normal readable text.

#Humans cannot easily read binary data directly.

#example - image files (.jpg, .png), audio files (.mp3, .wav), video files (.mp4, .avi), executable files (.exe), and many other types of files that contain data in a format that is not intended to be human-readable.

